config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'

  post '/endorsements' => 'endorsements#create'
  delete '/endorsements' => 'endorsements#destroy'

  delete '/skills/:id' => 'skills#destroy', as: :destroy_skills
  resources :users
end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :endorsed, class_name: User.name, foreign_key: :endorsed_user_id
  belongs_to :endorser, class_name: User.name, foreign_key: :endorser_user_id
  belongs_to :skill

  validates_presence_of :skill_id
  validates_presence_of :endorser
  validates_presence_of :endorsed
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  before_validation :set_slug, on: :create
  has_many :endorsements, dependent: :delete_all
  has_many :users, -> { distinct }, through: :endorsements

  def set_slug
    self.slug = name.to_s.gsub('&', ' and ').parameterize
  end

  def endorsements_count_by_user(user_id)
    endorsements.select { |e| e.endorsed_user_id == user_id }.count
  end

  def endorser_by_user?(endorsed_user_id, endorser_user_id)
    endorsements.select do |e|
      e.endorser_user_id == endorser_user_id &&
        e.endorsed_user_id == endorsed_user_id
    end.any?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true,
                    uniqueness: true,
                    format: {
                      with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,
                      message: 'not a valid email format'
                    }
  has_many :endorsements, foreign_key: :endorsed_user_id, dependent: :delete_all
  has_many :skills, -> { distinct }, through: :endorsements

  def add_endorsement(name, endorser_user_id)
    slug = name.to_s.gsub('&', ' and ').parameterize
    skill = skills.find { |s| s.slug == slug }
    skill = Skill.create(name: name, slug: slug) unless skill

    return if skill.endorser_by_user?(id, endorser_user_id)

    endorsements.create(
      skill_id: skill.id,
      endorser_user_id: endorser_user_id
    )
  end

  def remove_endorsement(name, endorser_user_id)
    slug = name.to_s.gsub('&', ' and ').parameterize
    skill = skills.find { |s| s.slug == slug }
    return unless skill

    user_endorsements = endorsements.where(
      skill_id: skill.id,
      endorser_user_id: endorser_user_id
    )
    user_endorsements.each(&:destroy)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :authorize

  def create
    if user.add_endorsement(endorsement_params[:skill_name], current_user.id)
      flash[:success] = 'Skill suggested.'
    else
      flash[:warning] = 'You already endorse this user for that skill.'
    end
    redirect_to user_path(user)
  end

  def destroy
    if user.remove_endorsement(endorsement_params[:skill_name], current_user.id)
      flash[:success] = 'Endorsement removed.'
    else
      flash[:warning] = 'Something went wrong, please try later.'
    end
    redirect_to user_path(user)
  end

  private

  def user
    @user ||= User.find(endorsement_params[:endorsed_user_id])
  end

  def endorsement_params
    params.permit(:skill_name, :endorsed_user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = 'Login successful'
      redirect_to '/'
    else
      flash[:warning] = 'Login Failed! Wrong email or password'
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authorize

  def destroy
    skill = Skill.find(params[:id])
    if skill.destroy
      flash[:success] = 'Skill deleted.'
    else
      flash[:warning] = 'Something went wrong, please try later.'
    end
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    descending = -1
    @skills = @user.skills.includes(:endorsements).sort_by do |s|
      s.endorsements_count_by_user(@user.id) * descending
    end
  end

  def new; end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:warning] = user.errors.full_messages
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Skills
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .session
      - if current_user
        | Signed in as 
        = link_to current_user.email, user_path(current_user)
        |  | 
        = link_to "Logout", '/logout'
        |  | 
        = link_to 'Users', users_path
      - else
        = link_to 'Login', '/login'
        |  | 
        = link_to 'Signup', '/signup'

    - flash.each do |key, value|
      div class="alert alert-#{key}"
        = value

    == yield

app/views/users/_skills_form.html.slim
= form_tag '/endorsements', class: 'endorsements' do |f|
  .form__group
    = label_tag :skill_name, 'Skill'
    = text_field_tag :skill_name
    = hidden_field_tag :endorsed_user_id, @user.id

  .form__group
    = submit_tag "Save"

app/views/users/index.html.slim
- @users.each do |user|
  .row
    = link_to user.email, user_path(user)

app/views/users/new.html.slim
h2 Signup

= form_for :user, url: '/users' do |f|
  .form__group
    = f.label :email, 'Email'
    = f.text_field :email

  .form__group
    = f.label :password, 'Password'
    = f.password_field :password

  .form__group
    = f.label :password_confirmation, 'Password Confirmation'
    = f.password_field :password_confirmation

  = f.submit "Submit"

app/views/users/show.html.slim
h1
  = @user.email

table.skills
  - @skills.each do |skill|
    tr
      td
        = skill.name
      td
        = skill.endorsements_count_by_user(@user.id)
      td
        - if current_user == @user
          = link_to 'X', destroy_skills_path(skill), method: :delete, data: { confirm: 'Are you sure?' }
        - elsif skill.endorser_by_user?(@user.id, current_user.id)
          = link_to '-', endorsements_path(skill_name: skill.name, endorsed_user_id: @user.id), method: :delete
        - else
          = link_to '+', endorsements_path(skill_name: skill.name, endorsed_user_id: @user.id), method: :post

= form_for :skill, url: '/endorsements', html: { id: :endorse_hidden_form } do |f|
  = f.hidden_field :name
  = hidden_field_tag :user_id, @user.id

= form_for :skill, url: '/endorsements', method: :delete, html: { id: :remove_endorse_hidden_form } do |f|
  = f.hidden_field :name
  = hidden_field_tag :user_id, @user.id

= render partial: 'skills_form'